name: "Continuous Integration"
on:
  - pull_request
  - push

jobs:
  run:
    name: "Test"
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['7.3', '7.4', '8.0']
        composer-versions: ['composer:v1', 'composer:v2']

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 1

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: ${{ matrix.composer-versions }}
          extensions: mbstring, xdebug, pcov

      - name: Install dependencies
        run: composer install --no-progress --no-suggest --prefer-dist

      - name: Run phpunit
        run: composer run test
